[project]
name = "phologtolabstreaminglayer"
version = "0.3.0"
description = "a complete but minimal python app that allows the user to take timestampped notes to labstreaminglayer with EventBoard functionality"
readme = "README.md"
requires-python = ">=3.9.13"
dependencies = [
    "attrs>=25.3.0",
    "keyboard>=0.13.5",
    "matplotlib>=3.9.4",
    "mne>=1.8.0",
    "mne-lsl>=1.6.1",
    "pillow>=11.3.0",
    "pyautogui>=0.9.54",
    "pyinstaller>=6.14.2",
    "pylsl>=1.17.6",
    "pystray>=0.19.5",
    "pyxdf>=1.17.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "flake8>=6.0.0",
]
